require("demaster.plugin_config.treesitter")
require("demaster.plugin_config.lualine")
require("demaster.plugin_config.telescope")
require("demaster.plugin_config.treesitter-context")
require("demaster.plugin_config.lsp")
require("demaster.plugin_config.oil")
require("demaster.plugin_config.harpoon")
require('leap').add_default_mappings()
